from screens.create_branch_page import BranchWindow
from screens.create_cause_page import CauseWindow
from screens.create_class_page import ClassWindow
from screens.create_class_to_parent import AddClassWindow
from screens.create_degree_page import DegreeWindow
from screens.create_department_page import DepartmentWindow
from screens.create_disconnection_page import DisconnectionWindow
from screens.create_institution_page import InstitutionWindow
from screens.create_main_page import MainWindow
from screens.create_neigborhood import NeighborhoodWindow
from screens.create_parent_class import ParentClassWindow
from screens.create_staff_branch_page import StaffBranchWindow
from screens.create_staff_page import StaffWindow
from screens.create_student_from_archive_page import StudentFromArchiveWindow
from screens.create_student_page import StudentWindow
from screens.create_workplace_page import WorkplaceWindow
from screens.create_workplace_to_staff import AddWorkplaceToStaff


